name: Build BMC firmware

on: workflow_dispatch

jobs:
  build:
    name: Build BMC firmware
    runs-on: ubuntu-latest



    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4

      - name: Setup ARM toolchain
        uses: danielpinto8zz6/setup-arm@v1
        with:
          gcc-version: '12.2-2022.11'

      - name: Build Firmware
        id: build-firmware
        run: make Release
        working-directory: BMC/E45_Hem_G_BMC_FW/Release

      - name: Check Release folder
        run: ls -l BMC/E45_Hem_G_BMC_FW/Release
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: bmc-firmware
          path: |
            BMC/E45_Hem_G_BMC_FW/Release/*.elf
            BMC/E45_Hem_G_BMC_FW/Release/*.map

