name: Build BMC firmware

on: workflow_dispatch

jobs:
  build:
    name: Build BMC firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-arm-none-eabi
          
      - name: Build Firmware
        id: build-firmware
        run: make Release
        working-directory: BMC/E45_Hem_G_BMC_FW/Release

      - name: Check Release folder
        run: ls -l BMC/E45_Hem_G_BMC_FW/Release
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: bmc-firmware
          path: BMC/E45_Hem_G_BMC_FW/Release/**/*.elf

